services:
  - type: web
    name: mxdownloader-mazenmix-8613887
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    renderSubdomainPolicy: enabled
    envVars:
      - key: CORS_ORIGINS
        value: "*"
